spring:
  profiles:
    active: dev

  batch:
    jdbc:
      initialize-schema: never
#    job:
#      enabled: false

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/**/*.xml

