spring:
  profiles:
    active: aws

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: true

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/**/*.xml

