spring:
  datasource:
    # mysql ver8 ??? com.mysql.cj.jdbc.Driver
    # ?? ??? com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_lilac_boot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_lilac_boot_dev
    password: 1234
  batch:
    jdbc:
      initialize-schema: never
#    job:
#      enabled: false

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/**/*.xml

logging:
  file:
    path: C:\lilac-batch-log
    max-size: 500MB
    max-history: 10
    name: batch.log
  level:
    root: info
    com.steelrain.lilac.batch: debug

